**Mini Project**
Airline Tweet Sentiment Classifier using Natural Language Processing**
---
**Notes:**
Use sample dataset:
https://github.com/salman1256/aimltraining/blob/main/Day-30/airline_tweets_sample.csv

---
# Steps:
1. Import libraries  
2. Load and explore dataset  
3. Clean and preprocess the text  
4. Convert text to numerical vectors (TF-IDF)  
5. Split into train and test sets  
6. Train a Logistic Regression model  
7. Evaluate accuracy and classification report  
8. Predict sentiment for new example tweets

In [328]:
# Step 1 a: Import Required Libraries
# Step 1 b: Download nltk required thing like stopwords
import pandas as pd
import re
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
# from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.linear_model import LogisticRegression
nltk.download('stopwords')
# nltk.download('wordnet')
# nltk.download('punkt')
# nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [329]:
#Step 2 a: Load DataSet
#Step 2 b: Check Data set  at least top 5 values
df = pd.read_csv('/content/sample_data/airline_tweets_sample.csv')
df.head()

                                                text sentiment
0  @United flight was delayed for 3 hours, worst ...  negative
1  Loved the service on @Delta, crew was super fr...  positive
2  @AmericanAir lost my luggage again, so disappo...  negative
3  Smooth boarding and on-time arrival. Great job...  positive
4  The seats were uncomfortable but staff was polite   neutral

In [330]:
df.isnull().sum()

text         0
sentiment    0
dtype: int64

In [331]:
# Step 3:
#Text Cleaning and Preprocessing
# For each tweet do:
# a. Convert to lowercase
# b. Remove URLs
# c. Remove special characters and numbers
# d. Remove stopwords (common words like *the, is, and* etc.)
# e. Apply **stemming** (reduce words to their root form)
ps = PorterStemmer()

In [332]:
def clean_text(text) :
  text=text.lower()
  text=re.sub(r"http\S+","",text)
  text=re.sub(r"www\S+","",text)
  text=re.sub(r"[^a-z\s]","",text)
  text="".join([ps.stem(word) for word in text.split() if word not in stopwords.words("english")])
  return text

In [333]:
df["clean_text"]=df["text"].apply(clean_text)
df["clean_text"].head()

0           unitflightdelayhourworstexperiever
1             loveservicdeltacrewsuperfriendli
2              americanairlostluggagdisappoint
3    smoothboardontimarrivgreatjobsouthwestair
4                      seatuncomfortstaffpolit
Name: clean_text, dtype: object

In [334]:
#Step: 4
#a) Convert text to numerical vectors (TF-IDF)
#b) check X,y and shape len
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(df['clean_text'])
y = df['sentiment']

In [335]:
print("X :")
print(X)

print("\nShape of X:", X.shape)
print("Length of X:", len(X.toarray()))

print("\ny (labels):")
print(y)

print("Shape of y:", y.shape)
print("Length of y:", len(y))

X :
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 30 stored elements and shape (30, 30)>
  Coords	Values
  (0, 28)	1.0
  (1, 16)	1.0
  (2, 1)	1.0
  (3, 22)	1.0
  (4, 21)	1.0
  (5, 14)	1.0
  (6, 12)	1.0
  (7, 2)	1.0
  (8, 9)	1.0
  (9, 13)	1.0
  (10, 23)	1.0
  (11, 24)	1.0
  (12, 6)	1.0
  (13, 8)	1.0
  (14, 11)	1.0
  (15, 26)	1.0
  (16, 17)	1.0
  (17, 0)	1.0
  (18, 5)	1.0
  (19, 20)	1.0
  (20, 18)	1.0
  (21, 15)	1.0
  (22, 3)	1.0
  (23, 19)	1.0
  (24, 27)	1.0
  (25, 10)	1.0
  (26, 4)	1.0
  (27, 7)	1.0
  (28, 25)	1.0
  (29, 29)	1.0

Shape of X: (30, 30)
Length of X: 30

y (labels):
0     negative
1     positive
2     negative
3     positive
4      neutral
5     negative
6     positive
7      neutral
8     positive
9     negative
10    negative
11    positive
12    positive
13    negative
14     neutral
15    positive
16    negative
17    positive
18    positive
19    negative
20     neutral
21    positive
22    negative
23     neutral
24    negative
25    positive
26    negative
27    positive
28     neutral
29    negative
Name: sentiment, dtype: object
Shape of y: (30,)
Length of y: 30

In [336]:
# Step 5: Split into train and test sets
# 80% training and 20% testing
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [337]:
# Step:6 Train a Logistic Regression model
# a: Create Logistic Model
# b: Train Logistic Model
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [338]:
#for test
# model=MultinomialNB()
# model.fit(X_train_vec,y_train)

In [339]:
#Step 7:
# Evaluate accuracy and classification report
# a. predict Model
# b. Precision, reacll, F1-Score for each sentiments
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
cnf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Accuracy:", acc)
print("Confusion Matrix:\n", cnf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.16666666666666666
Confusion Matrix:
 [[1 0 0]
 [1 0 0]
 [4 0 0]]
Classification Report:
               precision    recall  f1-score   support

    negative       0.17      1.00      0.29         1
     neutral       0.00      0.00      0.00         1
    positive       0.00      0.00      0.00         4

    accuracy                           0.17         6
   macro avg       0.06      0.33      0.10         6
weighted avg       0.03      0.17      0.05         6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [340]:
#Step 8: Predict sentiment for new example tweets
input_text=[
    "Excellent in-flight service and very helpful cabin crew.",
    "The ground staff at the gate were courteous and helpful during a last-minute boarding change." ,
    "The flight was delayed by over two hours, and there was no communication from the airline staff regarding the reason or estimated departure time.",
    "The seat was uncomfortable, and the in-flight entertainment system was not working for the entire duration of the flight." ,
    "While the flight was on time, the check-in process at the airport was chaotic and understaffed. It took me 30 minutes just to get my bag checked in. The airline should consider more staff at the counter during peak hours."
]
input_clean_text = [clean_text(text) for text in input_text]
input_clean_text_vec = tfidf.transform(input_clean_text)
predictions = model.predict(input_clean_text_vec)
print("Prediction :")
for text,prediction in zip(input_text,predictions):
  print(f"{text} --> {prediction}")

Prediction :
Excellent in-flight service and very helpful cabin crew. --> negative
The ground staff at the gate were courteous and helpful during a last-minute boarding change. --> negative
The flight was delayed by over two hours, and there was no communication from the airline staff regarding the reason or estimated departure time. --> negative
The seat was uncomfortable, and the in-flight entertainment system was not working for the entire duration of the flight. --> negative
While the flight was on time, the check-in process at the airport was chaotic and understaffed. It took me 30 minutes just to get my bag checked in. The airline should consider more staff at the counter during peak hours. --> negative

**Model is not Very Good because Accuracy 0nly 0.166. not even half.**