In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
data=pd.DataFrame({
    "Experience" : [1,2,3,4,5,np.nan,7,8,9,10],
    "Education" : ["Bachelor's","Bachelor's","Master's","PhD","Bachelor's",np.nan,"Bachelor's","Master's","PhD","Bachelor's"],
    "Salary" : [35000,40000,45000,55000,50000,50000,62000,70000,75000,76000]
})
data

   Experience   Education  Salary
0         1.0  Bachelor's   35000
1         2.0  Bachelor's   40000
2         3.0    Master's   45000
3         4.0         PhD   55000
4         5.0  Bachelor's   50000
5         NaN         NaN   50000
6         7.0  Bachelor's   62000
7         8.0    Master's   70000
8         9.0         PhD   75000
9        10.0  Bachelor's   76000

In [ ]:
X=data[["Experience","Education"]]
y=data["Salary"]

In [ ]:
num_cols=["Experience"]
cat_cols=["Education"]
numeric=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="mean")),
    ("scaler",StandardScaler())
])

categorical=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="most_frequent")),
    ("encoder",OneHotEncoder(handle_unknown="ignore"))
])

In [ ]:
prepro=ColumnTransformer([
    ("num",numeric,num_cols),
    ("cat",categorical,cat_cols)
])

pipe=Pipeline(steps=[
    ("preprocess",prepro),
    ("model",LinearRegression())
])

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Experience']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Education'])])),
                ('model', LinearRegression())])

In [ ]:
y_pred=pipe.predict(X_test)
y_pred

array([78560.10032088, 37232.84033489])

In [ ]:
#Evaluate the model
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)

print("MAE :",round(mae,2))
print("RMSE :",round(rmse,2))
print("R2 score :",round(r2,2))

MAE : 3163.63
RMSE : 3188.38
R2 score : 0.97

In [ ]:
#Predict for new employee
exp=int(input("Enter experience :"))
edu=input("Enter education :")
new_employee = pd.DataFrame({
    "Experience": [exp],
    "Education": [edu]
    })
predicted_salary = pipe.predict(new_employee)
print(f'Predicted salary is :',round(predicted_salary[0],2))

Enter experience :5
Enter education :Master
Predicted salary is : 55408.3

In [ ]:
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from sklearn.svm import SVR

In [ ]:
dat = pd.DataFrame({
    "EngineSize": [1.0, 1.2, 1.4, 1.6, 1.8, np.nan, 2.0, 2.2, 2.4, 2.6],
    "HorsePower": [68, 75, 90, 100, 110, 115, np.nan, 130, 150, 160],
    "FuelType": ["Petrol", "Diesel", "Petrol", "Diesel", "Petrol",
                 "Petrol", np.nan, "Diesel", "Petrol", "Diesel"],
    "FuelEfficiency": [20, 22, 19, 25, 18, 21, 23, 26, 17, 24]
})

In [ ]:
dat

   EngineSize  HorsePower FuelType  FuelEfficiency
0         1.0        68.0   Petrol              20
1         1.2        75.0   Diesel              22
2         1.4        90.0   Petrol              19
3         1.6       100.0   Diesel              25
4         1.8       110.0   Petrol              18
5         NaN       115.0   Petrol              21
6         2.0         NaN      NaN              23
7         2.2       130.0   Diesel              26
8         2.4       150.0   Petrol              17
9         2.6       160.0   Diesel              24

In [ ]:
X=dat[["EngineSize","HorsePower","FuelType"]]
y=dat["FuelEfficiency"]

In [ ]:
eng_cols=["EngineSize","HorsePower"]
#pow_cols=["HorsePower"]
fue_cols=["FuelType"]
numb=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="mean")),
    ("scaler",StandardScaler())
])

typ=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="most_frequent")),
    ("encoder",OneHotEncoder(handle_unknown="ignore"))
])

In [ ]:
preproc=ColumnTransformer([
    ("engine",numb,eng_cols),
    #("power",numb,pow_cols),
    ("fuel",typ,fue_cols)

])


pipe=Pipeline(steps=[
    ("preprocess",preproc),
#first model LR ng
#    ("model",LinearRegression())
#second model RFR ng
#    ("model",RandomForestRegressor(n_estimators=100,random_state=42))
#third model SVR
#    ("model",SVR(kernel='rbf',C=100,gamma=0.1))
#4th model GradientBoostingRegressor
    ("model",GradientBoostingRegressor(n_estimators=150,random_state=42,max_depth=3,learning_rate=0.1))
])

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('engine',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['EngineSize', 'HorsePower']),
                                                 ('fuel',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['FuelType'])])),
                ('model',
                 GradientBoostingRegressor(n_estimators=150, random_state=42))])

In [ ]:
y_pred=pipe.predict(X_test)
y_pred

array([21.70425524, 24.99992417])

In [ ]:
#Evaluate the model
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)

print("MAE :",round(mae,2))
print("MSE :",round(mse,2))
print("RMSE :",round(rmse,2))
print("R2 score :",round(r2,2))

MAE : 3.85
MSE : 15.56
RMSE : 3.95
R2 score : -1.49

In [ ]:
#Predict for new employee
Enginesize=float(input("Enter Engine Type :"))
Powerhorse=float(input("Enter Power Horse :"))
Fueltype=input("Enter Fuel Type :")
fuel_eff = pd.DataFrame({
    "Engine Type": [Enginesize],
    "Power Horse": [Powerhorse],
    "Fuel Type" : [Fueltype]
    })
predicted_eff = pipe.predict(fuel_eff)
#print(f'Predicted Fuel Efficiency is :',round(predicted_eff,2))
print(f"Predicted Fuel Efficiency is: {round(predicted_eff[0], 2)}")

Enter Engine Type :55
Enter Power Horse :55
Enter Fuel Type :55

ValueError: columns are missing: {'HorsePower', 'EngineSize', 'FuelType'}

In [ ]:
5