**We are going to write Multi Label Classification Example using TensorFlow**

In [154]:
import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [155]:
data={
    "overview":[
        "Friday the 13th",
        "American Horror Story",
        "The Dark Knight Rises",
        "The Emperor's New Groove",
        "Jurassic Park",
        "A Hero Saves the City from destruction",
        "A girl and boy become friends during war",
        "A funny sorry of collegues during office meet",
        "One Scary nights in a deserted place"

    ],
    "genres" :[["Horror"],["Drama","Horror"],["Action","Advanture"],["Comedy","Animation"],["Action","Advanture","Thriller"],["Action","Advanture"],["Romance","Drama"],["Comedy"],["Horror"]]
}

In [156]:
df=pd.DataFrame(data)
df

,overview,genres
0,Friday the 13th,[Horror]
1,American Horror Story,"[Drama, Horror]"
2,The Dark Knight Rises,"[Action, Advanture]"
3,The Emperor's New Groove,"[Comedy, Animation]"
4,Jurassic Park,"[Action, Advanture, Thriller]"
5,A Hero Saves the City from destruction,"[Action, Advanture]"
6,A girl and boy become friends during war,"[Romance, Drama]"
7,A funny sorry of collegues during office meet,[Comedy]
8,One Scary nights in a deserted place,[Horror]

In [157]:
tokenizer=Tokenizer(num_words=5000,oov_token="<OOV>")
tokenizer.fit_on_texts(df["overview"])
X=tokenizer.texts_to_sequences(df["overview"])
X=pad_sequences(X,maxlen=20,padding="post")

In [158]:
mlb=MultiLabelBinarizer()
y=mlb.fit_transform(df["genres"])

In [159]:
y

array([[0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])

In [160]:
#Create Model
model=tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=5000,output_dim=16,input_length=20),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(16,activation="relu"),
    tf.keras.layers.Dense(len(mlb.classes_),activation="sigmoid"),
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [161]:
#Compile model
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [162]:
history = model.fit (X,y,epochs=20)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 864ms/step - accuracy: 0.2222 - loss: 0.6919
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.2222 - loss: 0.6905
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.2222 - loss: 0.6891
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.2222 - loss: 0.6877
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.2222 - loss: 0.6862
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.2222 - loss: 0.6845
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.2222 - loss: 0.6828
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.2222 - loss: 0.6810
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.2222 - loss: 0.6792
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.2222 - loss: 0.6773
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.2222 - loss: 0.6754
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.2222 - loss: 0.6735
Epoch 13/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.2222 - loss: 0.6715
Epoch 14/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.2222 - loss: 0.6695
Epoch 15/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.2222 - loss: 0.6674
Epoch 16/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.2222 - loss: 0.6653
Epoch 17/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.2222 - loss: 0.6632
Epoch 18/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.2222 - loss: 0.6610
Epoch 19/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.2222 - loss: 0.6588
Epoch 20/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.2222 - loss: 0.6565

In [163]:
# Evaluate Model
loss,accuracy = model.evaluate(X,y)
print("Test Loss :",loss)
print("Test Accuracy :",accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - accuracy: 0.2222 - loss: 0.6543
Test Loss : 0.6542521119117737
Test Accuracy : 0.2222222238779068

In [176]:
#Prediction on a New Movie Overview
new_movie_overview = ['Adventure of Tom the cat']
seq=tokenizer.texts_to_sequences(new_movie_overview)
seq=pad_sequences(seq,maxlen=20,padding="post")
prediction=model.predict(seq)
prediction_labels=[mlb.classes_[i] for i in range(len(prediction[0])) if prediction[0][i] > 0.5]
print("Predicted Genres :",prediction_labels)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Predicted Genres : []

**Example 2**

Use this data set to write one more MultiLabel Classification prediction using Nueral Network

In [179]:
news_data = {
    "headline": [
        "Government launches new digital economy policy",
        "Star player wins championship after dramatic final",
        "Tech company releases AI-powered smartphone",
        "Stock market drops amid political tensions",
        "New environmental policy gains global support",
        "Space agency announces manned Mars mission"
    ],
    "topics": [
        ["Politics", "Economy", "Technology"],
        ["Sports"],
        ["Technology", "Business"],
        ["Economy", "Politics"],
        ["Environment", "Politics"],
        ["Science", "Technology"]
    ]
}

In [181]:
ndf=pd.DataFrame(news_data)
ndf.head()

,headline,topics
0,Government launches new digital economy policy,"[Politics, Economy, Technology]"
1,Star player wins championship after dramatic f...,[Sports]
2,Tech company releases AI-powered smartphone,"[Technology, Business]"
3,Stock market drops amid political tensions,"[Economy, Politics]"
4,New environmental policy gains global support,"[Environment, Politics]"

In [182]:
tokenizer=Tokenizer(num_words=5000,oov_token="<OOV>")
tokenizer.fit_on_texts(ndf["headline"])
X=tokenizer.texts_to_sequences(ndf["headline"])
X=pad_sequences(X,maxlen=20,padding="post")

In [183]:
mlbhl=MultiLabelBinarizer()
y=mlbhl.fit_transform(ndf["topics"])

In [184]:
#Create Model
model_hl=tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=5000,output_dim=16,input_length=20),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(16,activation="relu"),
    tf.keras.layers.Dense(len(mlbhl.classes_),activation="sigmoid"),
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [185]:
#Compile model
model_hl.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [186]:
history_hl = model_hl.fit (X,y,epochs=20)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 890ms/step - accuracy: 0.1667 - loss: 0.6940
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.1667 - loss: 0.6933
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.1667 - loss: 0.6927
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.1667 - loss: 0.6922
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.1667 - loss: 0.6915
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.1667 - loss: 0.6909
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 0.6903
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.0000e+00 - loss: 0.6897
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.0000e+00 - loss: 0.6890
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.0000e+00 - loss: 0.6883
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 0.6876
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 0.6871
Epoch 13/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.0000e+00 - loss: 0.6865
Epoch 14/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.1667 - loss: 0.6859
Epoch 15/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.1667 - loss: 0.6853
Epoch 16/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.1667 - loss: 0.6847
Epoch 17/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.1667 - loss: 0.6840
Epoch 18/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.1667 - loss: 0.6833
Epoch 19/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.1667 - loss: 0.6826
Epoch 20/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.1667 - loss: 0.6819

In [187]:
# Evaluate Model
loss,accuracy = model_hl.evaluate(X,y)
print("Test Loss :",loss)
print("Test Accuracy :",accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.1667 - loss: 0.6812
Test Loss : 0.6812097430229187
Test Accuracy : 0.1666666716337204

In [188]:
#Prediction on a News topics
news_topics = ['Fire broke at Warehouse near Port in Lubenon']
seq_news=tokenizer.texts_to_sequences(news_topics)
seq_news=pad_sequences(seq_news,maxlen=20,padding="post")
prediction=model_hl.predict(seq_news)
prediction_topics=[mlbhl.classes_[i] for i in range(len(prediction[0])) if prediction[0][i] > 0.5]
print("Predicted News Topics :",prediction_topics)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
Predicted News Topics : ['Business', 'Politics', 'Technology']