**Steps for Modelling**


1.   Creating the Model
2.   Compailing the Model
3.   Define a loss Function
4.   Setting up an Optimizer
5.   Fiding best learning size
6.   Creating Evaluation Metrics
7.   Fitting Model
8.   Improve Model

***Predict Heart Disease***


*   Load Dataset
*   Split features and test
*   Train Test Split
*   Scale Features

In [ ]:
import pandas as pd, numpy as np, tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [ ]:
data=pd.read_csv('/content/sample_data/heart.csv')
data

   age  sex  chol  trestbps  thalach  target
0   52    1   200       130      150       1
1   58    0   240       150      140       1
2   60    1   180       140      145       0
3   48    1   190       120      160       0
4   50    0   220       125      155       1
5   65    1   210       160      130       0
6   54    1   230       135      150       1
7   46    0   205       128      162       0
8   66    1   250       155      120       0
9   57    0   195       132      165       1

In [ ]:
X=data.drop('target',axis=1)
y=data['target']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
#Create Model
model=tf.keras.Sequential([
    tf.keras.layers.Dense(16,activation='relu',input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(8,activation ='relu'),
    tf.keras.layers.Dense(1,activation ='sigmoid')])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
#compile model
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
# Train the model
history_model = model.fit(X_train,y_train,epochs=100,verbose=0,validation_data=(X_test,y_test))

In [ ]:
#Evaluate the Model
loss,accuracy = model.evaluate(X_test,y_test)
print(f'Loss:{loss}, Accurancy:{accuracy}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.4970
Loss:0.4970283806324005, Accurancy:1.0

**Example 2:**

*Bank Customer Exit Prediction.
Based on given data using Neural Network Binary Classifier find out is a customer going to stay or leave stay: (Exited=0) and leave (Exited=1)
Predict the result for new data as well at end

In [ ]:
bank_dat=pd.read_csv('/content/sample_data/bank_churn.csv')
bank_dat

,CreditScore,Geography,Gender,Age,Balance,NumOfProducts,EstimatedSalary,Exited
0,600,France,Male,40,60000,1,50000,0
1,700,Spain,Female,45,70000,2,60000,0
2,800,Germany,Female,38,80000,1,70000,1
3,400,France,Male,30,30000,1,40000,1
4,550,Spain,Male,50,40000,2,42000,0
5,760,France,Female,36,75000,1,72000,0
6,680,Germany,Female,42,68000,2,65000,1
7,710,Spain,Male,39,72000,1,54000,0
8,640,France,Male,48,50000,2,50000,1
9,590,Germany,Female,52,45000,1,47000,1

In [ ]:
le=LabelEncoder()
bank_dat['Gender']=le.fit_transform(bank_dat['Gender'])
bank_dat=pd.get_dummies(bank_dat,columns=['Geography'])
X=bank_dat.drop('Exited',axis=1)
y=bank_dat['Exited']

In [ ]:
# data_one_hot=pd.get_dummies(bank_dat)
# data_one_hot.head(10)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
bank_model=tf.keras.Sequential([
    tf.keras.layers.Dense(16,activation='relu',input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(8,activation ='relu'),
    tf.keras.layers.Dense(1,activation ='sigmoid')])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
bank_model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])
bank_model.summary()

Model: "sequential_19"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_57 (Dense)                │ (None, 16)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_58 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_59 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 305 (1.19 KB)

 Trainable params: 305 (1.19 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
bank_model_history=bank_model.fit(X_train,y_train,epochs=100,verbose=0,validation_data=(X_test,y_test))

In [ ]:
new_customer=pd.DataFrame({
    "CreditScore":600,
    "Geography":["France"],
    "Gender":["Male"],
    "Age": 42,
    "Balance":10000,
    "NumOfProducts":1,
    "EstimatedSalary":5000
})

#Encode and scale same as befor
new_customer['Gender']=le.transform(new_customer['Gender'])

#Add missing dummy column
new_customer=pd.get_dummies(new_customer,columns=['Geography'],drop_first=True)
for col in [c for c in X.columns if c not in new_customer.columns]:
  new_customer[col]=0

new_customer = new_customer[X.columns] # same order
new_scaled = scaler.transform(new_customer)

#Prediction for remaining
pred = bank_model.predict(new_scaled)
if pred[0][0] > 0.5:
  print("Customer will leave")
  print(pred[0][0])
else:
  print("Customer will stay")
  print(pred[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
Customer will leave
0.99685025